[package]
name = "simulator"
version = "0.1.1"
edition = "2021"

[dependencies]
eframe = { version = "0.29.1", features = ["glow"] }
egui = "0.29.1"
winapi = { version = "0.3.9", features = ["winuser", "windef"] }
rapier2d = "0.22.0"
nalgebra = "0.33.2"
crossbeam = "0.8.4"
